name: Docker Image CI NewsBackOffice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: newsbackoffice
      run: docker build -t newsbackoffice -f NewsBackOffice/Dockerfile .

  deploy:
     
    needs: build
    
      runs-on: [self-hosted]
        steps:
          - name: Pull latest image & restart container
            run: |
              docker stop newsbackoffice || true
              docker rm newsbackoffice || true
              docker pull newsbackoffice:latest || true 
              docker run -d --name newsbackoffice -p 8080:8080 newsbackoffice
