name: Docker CI/CD NewsBackOffice

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t newsbackoffice:latest -f NewsBackOffice/Dockerfile .

      - name: Stop & remove old container
        run: |
          docker stop newsbackoffice || true
          docker rm newsbackoffice || true

      - name: Run new container
        run: docker run -d \
            --name newsbackoffice \
            --network news-network \
            --env-file /home/stoppenkastserver/docker_projects/LazyNewsBO/.env \
            -p 8080:8080 \
            newsbackoffice:latest
