name: Docker Image CI NewsBackOffice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: sudo docker build -t newsbackoffice:latest -f NewsBackOffice/Dockerfile .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop & remove old container (ignore errors)
        run: |
          sudo docker stop newsbackoffice || true
          sudo docker rm newsbackoffice || true

      - name: Run new container
        run: |
          sudo docker run -d --name newsbackoffice -p 8080:8080 newsbackoffice:latest
